image: maven:latest

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

cache:
  paths:
    - .m2

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean install
